### ISSUE TITLE
Support for compton and other compositors

### ISSUE THREAD

**Issue by traptivist** [dylanaraps/wal#11]
I use compton and urxvt as terminal emulator and I have this lines in my .Xresources 
`URxvt.depth:` `32`
`URxvt.background:` `[95]#232c31`
to enable `true` transparency for urxvt there but after run this script compton did't take any effect and there is no transparency, there is a way or somthing to modified to make true transparency working again? if its help I'm using bspwm and compton & in the .xinitrc

**Comment by dylanaraps** [comment]
Fixed.

I've added a new flag called `-a` that takes a transparency value.

```sh
# 95 transparency
wal -i img.png -a 95
```

Note: This only seems to work with URxvt.

Note:  `-a` also sets `URxvt.depth` to `32`.

**Comment by traptivist** [comment]
Awesome thanks Dylan!
