### ISSUE TITLE
Rofi transparency ineffective 

### ISSUE THREAD

**Issue by KST123ABC** [dylanaraps/wal#13]
Hello,

ARGB usually works in Rofi. Despite editing color codes in Wal, I have been unable to replicate this stock feature.

I am the fellow who emailed you :P

**Comment by dylanaraps** [comment]
Done!

Sorry this took so long, I've been extremely busy.

You can now use the `-a` flag to change the transparency of Rofi windows (as well as terminals).

Example:

```sh
# 90 transparency
wal -i IMG -a 90
```

**Comment by KST123ABC** [comment]
No problem at all! It's a minor feature but very nice to have. Thanks for your diligence. 

Will test when I get the chance :+1:
