### ISSUE TITLE
Issue with termite

### ISSUE THREAD

**Issue by dbkblk** [dylanaraps/wal#16]
Hi,
I was trying several terminal emulators lately and want to keep termite + zsh.
I have added the code `(wal -r &)` in .zshrc and it works well with every terminal emulator so far, except that on termite, each time I open a new window, this text is displayed on the top:
`]708;#12100A`

I've isolated the source and it comes from your script. Unfortunately, I cannot manage to silence the output, because it would not apply the theme.

Do you have any idea?
Thank you for the script, which really improve graphics of i3.

**Comment by AuditeMarlow** [comment]
Have you tried the `-t` flag?

```sh
Flags:
  -t                      Fix artifacts in VTE Terminals. (Termite, xfce4-terminal)
```

**Comment by dbkblk** [comment]
Oh! Indeed, it works. I'm sorry to make you loose your time.

You should add this unformation under the command line in "Applying the
theme to new terminals." to make it more apparent.

2017-03-08 15:12 GMT+01:00 Niek den Breeje <notifications@github.com>:

**Comment by dylanaraps** [comment]
Will do, thanks for the suggestion.
