### ISSUE TITLE
Imagemagick failed to generate a 16 color palette for

### ISSUE THREAD

**Issue by markitoxs** [dylanaraps/wal#18]
Hey, quick one, do you have a workaround for whenever imagemagick cant generate a full palette? I have a lot of images where it just falls short of a few, so maybe it could approximate?

If not feel free to close this.

**Comment by markitoxs** [comment]
Here, I found an example from a file that you should have:

http://i.imgur.com/MzjsvnW.jpg

**Comment by dylanaraps** [comment]
I've come up with a solution. Do you have any other wallpapers that fail which I can use for testing?

**Comment by dylanaraps** [comment]
Fixed.

`wal` will now loop, each time trying a larger palette size until it finds 16 total colors. I've tried this with a dozen or so wallpapers that failed previously and the results are really good. :)

**Comment by markitoxs** [comment]
Just pulled code, works great, thank you!
