### ISSUE TITLE
wal2iterm colors are not accurate

### ISSUE THREAD

**Issue by dhagerty9009** [dylanaraps/wal#20]
<img width="1280" alt="screen shot 2017-04-01 at 8 20 03 pm" src="https://cloud.githubusercontent.com/assets/495534/24583465/dd00c0bc-1718-11e7-8275-0a5be794b46f.png">
<img width="1280" alt="screen shot 2017-04-01 at 8 20 10 pm" src="https://cloud.githubusercontent.com/assets/495534/24583466/dd01e262-1718-11e7-9f92-0fcc0e7ff711.png">

So, the latest update to the script at least has colors that are not inverted, but there is still something not right, as shown in the screenshots.

**Comment by dylanaraps** [comment]
Try out the latest version of the script, the issue could be that the colorspace is being set wrong. I've checked the RGB values myself and they are correct.

**Comment by dhagerty9009** [comment]
I've gone to terminal.sexy and imported the colorscheme being generated. Here's the link: http://terminal.sexy/#vpaC1szNvpaCKFKxRmuqrj-vQZe0mZ6WtLS01szNZmZmKFKxRmuqrj-vQZe0mZ6WtLS01szN

Here's the wallpaper I'm trying to use: http://i.imgur.com/H7SQr5Z.jpg (it's from that one /r/unixporn post).

Here's a zip of my wal cache: [wal.zip](https://github.com/dylanaraps/wal/files/888138/wal.zip)

I'm not really sure what is going wrong, but if there's anything I can do to help, let me know.

**Comment by FabriceCastel** [comment]
Took me a while to figure out why the palettes I was getting in iterm were total garbage...

Pulled the latest and it seems to work now :+1:

**Comment by dylanaraps** [comment]
The script still chokes when given some schemes. I've figured out the issue and I'm working on a fix.

**Comment by dylanaraps** [comment]
The bug is caused by me trying to do floating point math in bash by "faking" it. It works in 90% of cases but chokes on some colors since the decimal place is put in the wrong location.

I've fixed the issue by adding `bc` as a dependency. We now do floating point properly and it works! (Who would've thought?)

**Comment by dylanaraps** [comment]
Ok.

I've written a new function to fake floating point math, the difference this time is that the results of the function are actually correct. I've tested the function against `bc` and the results are identical. This allows us to once again remove the `bc` dependency from `wal2iterm`.  

Can you guys test the latest version of `wal2iterm` and let me know if it still all works correctly. If there are still issues (there shouldn't be) then I'll revert this change and go back to using `bc`.

**Comment by dhagerty9009** [comment]
👌 I'll test tomorrow.
