### ISSUE TITLE
Interpreting backslashs in the script provided to -o

### ISSUE THREAD

**Issue by peterhen0** [dylanaraps/wal#21]
I use font awesome in my lemonbar so there backslash terms (\uF094) included. When I put use wal-set or any other script for the -o flag, it displays the text after the backslash and not the intended character. It works if I call wal-set in a separate line though.

**Comment by dylanaraps** [comment]
I can't seem to reproduce this, can you give me the commands you use and also your script?

**Comment by vendion** [comment]
It seems I'm having similar issues.  Here are the relevant scripts:

Herbstluftwm config: http://sprunge.us/gOAU
Wrapper for Lemonbar: http://sprunge.us/KAdc
Lemonbar script: http://sprunge.us/EOLI
Lemonbar widgets: http://sprunge.us/ADHT
wal-set script: http://sprunge.us/ZSGT

Screenshot of lemonbar when wal-set script is called via `-o` flag
![2017-04-03-21 12 30-screenshot](https://cloud.githubusercontent.com/assets/145018/24637884/6332c3e8-18b2-11e7-859b-c0f1152f06a1.png)

Screenshot of lemonbar when wal-set script is called by itself
![2017-04-03-21 14 22-screenshot](https://cloud.githubusercontent.com/assets/145018/24637897/89ae3b7e-18b2-11e7-93c8-3564cad23386.png)

**Comment by peterhen0** [comment]
vendion is describing exactly what I was experiencing.

**Comment by dylanaraps** [comment]
The best solution to this problem is to remove `-o` entirely and instead encourage users to use their shell's syntax. I don't think it's possible for me to fix `-o` based on how it currently works.

```sh
# Old (-o)
wal -i ~/Pictures -o "~/bin/wal-set"

# New
# "&&" makes `wal-set` only run if `wal` runs successfully.
wal -i ~/Pictures && ~/bin/wal-set
```

What do you guys think?

**Comment by vendion** [comment]
I don't know if that will fix @peterhen0 problem.

In my case while that is basically what I will need to do, but that syntax doesn't work in Herbstluft configuration file (basically a shell script).  This is more of a problem with how the `spawn` command for `herbstclient` works, where it it picky about quotes, escapes, and special characters like `&`.  I guess I could make a shell script that calls `wal` then my script to update Herbstluft and lemonbar's colors.

**Comment by dylanaraps** [comment]
Ah, I see.

I'll try and fix `-o` then. :+1:

**Comment by dylanaraps** [comment]
Try out the latest version of `wal`, the issue *should* be fixed. `wal` now launches the script using another `bash` instance. This should fix all of the issues above.

Please test it out and let me know! :)

**Comment by peterhen0** [comment]
Thanks for all your work!

But this didn't seem to fix the issues. I realized I also still have the issue even when using `&&` to compose the two commands which is odd. It still needs to be on two separate lines

**Comment by dylanaraps** [comment]
Weird.

I'm not sure why this isn't working. It should work just fine on paper. I'll keep at it to see if I can figure out what's going wrong.

**Comment by vendion** [comment]
@dylanaraps I just grabbed the latest from master and tried it as well and have the same results.  I agree this is odd, that having it be handled in it's own instance of bash does not help matters.

**Comment by dylanaraps** [comment]
Try out the latest version, this could very well be a locale related issue. `wal` sets the locale to `C` at the start of the script since disabling unicode support in bash makes the script execute up to 3 times faster.

I've pushed a change that sets the locale back to the system's default before running the `wal-set` script. Hopefully this fixes the issue.

Thanks for being so patient guys, sorry that you have to keep testing versions of `wal`. 📦 

Please test it out and let me know!

**Comment by vendion** [comment]
That works!

Setting the locale would explain why it was breaking, as the Font Awesome fonts require unicode to render.

No worries about having to keep testing, I know how these things go sometimes.

**Comment by dylanaraps** [comment]
Awesome!

I'll wait for @peterhen0 to test it out before closing this issue.

**Comment by peterhen0** [comment]
Works like a charm now. Thanks!

**Comment by dylanaraps** [comment]
No problem!
