### ISSUE TITLE
Not changing wallpaper on XFCE

### ISSUE THREAD

**Issue by dabluecaboose** [dylanaraps/wal#25]
Hey!  Love the work, I'm very excited to start using wal more often.  One small issue I'm running into is that wal doesn't seem to be actually changing the currently set wallpaper when I run it.  I'll run it a few times, and it will cycle through the images and the colors, but it fails to actually change my desktop background.  Hope you can help me figure this one out!

**Comment by dylanaraps** [comment]
- Do you have `xprop` installed? 
- Do these commands work?
 

```sh
# Change the path at the end to an image locarion.
xfconf-query --channel xfce4-desktop --property /backdrop/screen0/monitor0/image-path --set /path/to/img.jpg
xfconf-query --channel xfce4-desktop --property /backdrop/screen0/monitor0/workspace0/last-image --set /path/to/img.jpg

```

**Comment by dabluecaboose** [comment]
Xprop is installed.  The second command works, but not the first one.

**Comment by dylanaraps** [comment]
Try out the latest version of `wal`. The issue should be fixed.

**Comment by dabluecaboose** [comment]
Nailed it!  Thanks for the help.  Really loving this.  Keep up the good work!

**Comment by dylanaraps** [comment]
Thanks! :)
