### ISSUE TITLE
wal settings keep gitk from starting

### ISSUE THREAD

**Issue by vKnmnn** [dylanaraps/wal#31]
i don't know if this is an issue with wal, but i noticed that i cannot run gitk whenever i have run wal and my setup is different from the default.
The error-message is this: 

```
$ gitk
application-specific initialization failed: bad cursor spec "#EECCAC"
Error in startup script: bad cursor spec "#EECCAC"
    (database entry for "-cursor" in widget ".")
    invoked from within
"load /usr/lib/libtk8.6.so Tk"
    ("package ifneeded Tk 8.6.6" script)
    invoked from within
"package require Tk"
    (file "/usr/bin/gitk" line 10)
```

the color #EECAC keeps changing and is always the last line of the corresponding file in `$HOME.cache/wal/schemes/* `
my settings for wal include: `(wal -rtq &)` 
`(wal -tq -i $HOME/.cache/wal/wal) `
`. $HOME.cache/wal/colors.sh`

**Comment by dylanaraps** [comment]
Fixed.

**Comment by vKnmnn** [comment]
i get another error using latest git release. it's not a bad cursor spec anymore, but a bad color.
#11150B is the first line in colors.sh at the moment.
```
application-specific initialization failed: unknown color name "[50]#11150B"
Error in startup script: unknown color name "[50]#11150B"
    (database entry for "-background" in widget ".")
    invoked from within
"load /usr/lib/libtk8.6.so Tk"
    ("package ifneeded Tk 8.6.6" script)
    invoked from within
"package require Tk"
    (file "/usr/bin/gitk" line 10)

```

**Comment by dylanaraps** [comment]
Try the latest master, sorry for closing this early.

**Comment by vKnmnn** [comment]
confirm fixed. thank you!
