### ISSUE TITLE
Plugin for Hyper terminal

### ISSUE THREAD

**Issue by dneustadt** [dylanaraps/wal#33]
Just in case anyone's looking for an integration with [Hyper](https://github.com/zeit/hyper) terminal:
I wrote a tiny [plugin](https://github.com/dneustadt/hyper-wal) that will pull the cached colorscheme into Hyper.

[hyper-wal](https://github.com/dneustadt/hyper-wal)

**Comment by dylanaraps** [comment]
We should add a section to the README about plugins that work with `wal`. I'll add it to my TODO list.

**Comment by dylanaraps** [comment]
Added a section to the README.
