### ISSUE TITLE
vim-airline support? [feature-request]

### ISSUE THREAD

**Issue by Iambecomeroot** [dylanaraps/wal#37]
I appreciate your adding a vim theme; it is very nice. However, [vim-airline](https://github.com/vim-airline/vim-airline) seems to be able to use hex colours completely ignoring my terminal colours. Is it possible to get a vim-airline theme? If not, is there an easy way to fix this?

**Comment by dylanaraps** [comment]
I'll add this sometime tomorrow :+1:

**Comment by dylanaraps** [comment]
Done!

(This should "just work" once you update the package inside vim)

**Comment by Iambecomeroot** [comment]
Awesome! Thanks!

**Comment by Iambecomeroot** [comment]
Is it possible to invert what has a coloured background and what has the terminals background? Now, the current buffer is the only one with a dark background and, if you look at my screenshot, I would like "NORMAL" and "66% ..." to have the pink background and the rest of the bar to be dark.
![screenshot_2017-05-08_11-42-29](https://cloud.githubusercontent.com/assets/8503756/25809578/ca4cd3ec-33e3-11e7-9417-2773b8bf634e.png)

Sorry for being such trouble.

**Comment by dylanaraps** [comment]
Fixed. :)

**Comment by Iambecomeroot** [comment]
You're pretty awesome.

**Comment by Iambecomeroot** [comment]
You're pretty awesome.

**Comment by Iambecomeroot** [comment]
Actually I was looking for something more like this:

```
" wal Airline
let g:airline#themes#wal#palette = {}

let s:N1 = [ '', '', 255, 10, 'BOLD' ]
let s:N2 = [ '', '', 10, 0 ]

let s:I1 = [ '', '', 255, 8, 'BOLD' ]
let s:I2 = [ '', '', 8, 0 ]

let s:V1 = [ '', '', 255, 10, 'BOLD' ]
let s:V2 = [ '', '', 10, 0 ]

let s:R1 = [ '', '', 255, 20, 'BOLD' ]
let s:R2 = [ '', '', 20, 0 ]

let g:airline#themes#wal#palette.normal  = airline#themes#generate_color_map(s:N1, s:N2, s:N2)
let g:airline#themes#wal#palette.insert  = airline#themes#generate_color_map(s:I1, s:I2, s:I2)
let g:airline#themes#wal#palette.visual  = airline#themes#generate_color_map(s:V1, s:V2, s:V2)
let g:airline#themes#wal#palette.replace = airline#themes#generate_color_map(s:R1, s:R2, s:R2)

" Inactive mode
let s:IN1 = [ '', '', 255, 8 ]
let s:IN2 = [ '', '', 8, 0 ]

let s:IA = [ s:IN1[1], s:IN2[1], s:IN1[3], s:IN2[3], '' ]
let g:airline#themes#wal#palette.inactive = airline#themes#generate_color_map(s:IA, s:IA, s:IA)

" Warnings
let s:WI = [ '', '', 66, 1, 'BOLD' ]
let g:airline#themes#wal#palette.normal.airline_warning  = s:N1
let g:airline#themes#wal#palette.insert.airline_warning  = s:WI
let g:airline#themes#wal#palette.visual.airline_warning  = s:WI
let g:airline#themes#wal#palette.replace.airline_warning = s:WI

let g:airline#themes#wal#palette.normal.airline_error  = s:WI
let g:airline#themes#wal#palette.insert.airline_error  = s:WI
let g:airline#themes#wal#palette.visual.airline_error  = s:WI
let g:airline#themes#wal#palette.replace.airline_error = s:WI
```

However, there is very little contrast between the background and foreground in those areas with `255` when the colours picked from the image are very light. Do you know how to replace `255` with the terminal background? `0` seems to work for `ctermbg` but not `ctermfg`. Thanks.

**Comment by dylanaraps** [comment]
Try the latest master.

**Comment by Iambecomeroot** [comment]
The buffers still seem backwards imo. It looks like the open buffer is the only one not highlighted.
![screenshot_2017-05-11_19-35-50](https://cloud.githubusercontent.com/assets/8503756/25974777/28d6d04e-3681-11e7-8e8d-2c9230ebdf9c.png)

**Comment by dylanaraps** [comment]
Try the latest master again.

![poo](https://cloud.githubusercontent.com/assets/6799467/25974939/df9d2af4-36ee-11e7-817f-6ba4cf4c494c.png)

**Comment by Iambecomeroot** [comment]
Thanks again. Nothing can be done about the sometimes poor contrast I suppose?
![screenshot_2017-05-12_19-15-33](https://cloud.githubusercontent.com/assets/8503756/26018800/66f494c6-3747-11e7-8dce-4df8452fd2a6.png)

**Comment by dylanaraps** [comment]
Update 'wal' to the latest version and the contrast should be better. (The
script and the vim scheme)

**Comment by Iambecomeroot** [comment]
You're right it is a lot better. Thanks for putting up with all my requests.

**Comment by Iambecomeroot** [comment]
One last thing: After I modify a file, the buffer gets unhighlighted until I write the file. The first scrot is before write and the second is after. I just upgraded the plugin so it should be the latest version.
![screenshot_2017-05-19_17-36-10](https://cloud.githubusercontent.com/assets/8503756/26265962/b81d776a-3cb9-11e7-8d37-ef4af528da49.png)
![screenshot_2017-05-19_17-36-26](https://cloud.githubusercontent.com/assets/8503756/26265963/b81e6ab2-3cb9-11e7-873b-bb5cf3b0de00.png)

**Comment by dylanaraps** [comment]
Fixed.

**Comment by Iambecomeroot** [comment]
Working. Thanks.
