### ISSUE TITLE
Regarding rofi and reboot

### ISSUE THREAD

**Issue by notaduck** [dylanaraps/wal#4]
Hi again. it seem like rofi's colorscheme isn't persistent after reboots

**Comment by dylanaraps** [comment]
Have you added this line to your startup file?

https://github.com/dylanaraps/wal#making-the-colorscheme-persist-on-reboot

**Comment by notaduck** [comment]
I added it to .xinitrc and `wal -r` to my .bashrc file

**Comment by dylanaraps** [comment]
I just tested it and it works fine.

Do you have rofi color settings in a config file by any chance? I have a feeling that the issue is related to the rofi config file overwriting `wal` on boot.

**Comment by dylanaraps** [comment]
Ping @notaduck

**Comment by notaduck** [comment]
Sry for the late reply again !
but yes I'm still having trouble with this. I tried to outcomment my rodi color sceme from `.extend.Xressources`, then loaded my new wallpaper with `wal -i /path/here` and checked the colors were loaded, and then rebooted my machine and then rofi were back to defaulta again.

**Comment by dylanaraps** [comment]
Can you send me your Rofi config file as well as the files that contain `wal` commands? I can probably reproduce this using your configs.

**Comment by AuditeMarlow** [comment]
Are you merging Xresources files before you load wal in your xinitrc? I've noticed that if you merge Xresources after wal, the colours indeed do not load after reboot.

**Comment by hallgat89** [comment]
I found some similar problem:
1. I used an image which caused a problem during color generation. (index == 10) happened.
It generated a terminal colorscheme, but rofi changed to the default theme. (some greyish thing)
2. I deleted .cache/wall folder.
3. Since then rofi doesn't change its theme.
