### ISSUE TITLE
wal not launching on i3 by boot or script

### ISSUE THREAD

**Issue by RorixRebel** [dylanaraps/wal#42]
Having an issue while using wal and polybar - not sure if the combo is the problem but this is my setup.

i3 config

    exec --no-startup-d wal -q -t -i ~/Pictures

wal installed on

    wal: /usr/bin/wal

tried launching it via i3 with a key

    bindsym $mod+w         exec wal -i $HOME/Pictures

Thing is if i run a script or manually do it via terminal everything works out so at this point im out of ideas. Also tried to put the scripts or wal command on the .xinitrc so im at a loss.

Tried to put it inside a script to cycle it - didnt work.

```
# Start wal
while true
do 
    wal -q -t -i ~/Pictures -o ~/.config/i3/wal-set
    #restart polybar so it gets new colors from xresources
    ~/.config/polybar/launch.sh
    sleep 15m
done
```

let me know and i can provide more details

**Comment by apartypooper** [comment]
I can repeat the issue. It seems wal kills itself in kill_old() when called within i3 config.

I3 executes wal with "/bin/sh -c [path]/wal [options]" which kill_old() kills. A quick (dirty) fix could be replacing the awk line

pids=($(ps aux | awk '(!/ awk/) && /wal / {print $2}'))

with

pids=($(ps aux | awk '(!/ awk/) && /bash.*wal / {print $2}'))

**Comment by RorixRebel** [comment]
Verified, the fix works.
thanks!
