### ISSUE TITLE
Verify /dev/pts/* are writable by the user

### ISSUE THREAD

**Issue by apartypooper** [dylanaraps/wal#44]
Wal tries to change settings for all terminals which may cause unnecessary warnings like:
`[...]/wal: line 194: /dev/pts/51: Permission denied`

This could be avoided by checking the write permission first:
`[[ -w "$term" ]] && printf "%b" "$sequences" > "$term" &`

**Comment by dylanaraps** [comment]
Added! 

Thanks :+1:
