### ISSUE TITLE
Allow 256-color support for vim

### ISSUE THREAD

**Issue by undying-fish** [dylanaraps/wal#46]
Might be minor in the long term, not sure, but the color schemes generated by wal seem to lock t_Co to 16 no matter what you do to it later in .vimrc, causing incompatibilities with plugins like [chrisbra/Colorizer](http://github.com/chrisbra/Colorizer).

**Comment by dylanaraps** [comment]
Try the latest master.

**Comment by undying-fish** [comment]
Working as intended.
