### ISSUE TITLE
When running wal text placed in terminal

### ISSUE THREAD

**Issue by JarrColl** [dylanaraps/wal#55]
when i run the wal command it adds text when it changes a terminals colour scheme even when I
(wal -r &) on openning of terminal

]708;#081552

**Comment by dylanaraps** [comment]
Add `-t` to your `wal` commands.

**Comment by Mr-SD** [comment]
I experienced the same issue. Perhaps this should be added to the ReadMe

**Comment by dylanaraps** [comment]
It's in the usage and it's listed in the README.

https://github.com/dylanaraps/wal#setup

My focus has been moved to https://github.com/dylanaraps/pywal
