### ISSUE TITLE
XFCE issues

### ISSUE THREAD

**Issue by krook1024** [dylanaraps/wal#6]
Hi. Setting the wallpaper in XFCE does not work, instead of
`xfconf-query --channel xfce4-desktop --property /backdrop/screen0/monitor0/image-path`
I have to use
`xfconf-query --channel xfce4-desktop --property /backdrop/screen0/monitor0/workspace0/last-image`.
Another problem is, let's say I'm in the ~/Pictures directory and I do 
`wal -t -i image.jpg`
the xfce configuration will receive only `image.jpg` which is not an absolute path therefore it's not going to work.
Can you please fix?

**Comment by dylanaraps** [comment]
Can you run both of these commands and let me know the output?

```sh
# Change `/path/to/img.jpg` to a valid image.
xfconf-query --channel xfce4-desktop --property /backdrop/screen0/monitor0/image-path --set "/path/to/img.jpg"
echo "$?"
```

Basically, I want to know if the incorrect wallpaper command exits on an error or not.

**Comment by dylanaraps** [comment]
I just pushed a fix for both issues to master.

wal now works all relative/absolute paths.

```sh
# Absolute path.
wal -i ~/Pictures/Wallpapers/10.jpg
wal -i ~/Pictures/Wallpapers/

# Relative path.
cd Pictures
wal -i Wallpapers/10.jpg
wal -i Wallpapers/

# File or current dir
cd Wallpapers
wal -i 10.jpg
wal -i .

# Backwards Dir or file
wal -i ../Avatars/1.png
wal -i ../Avatars/
```

I haven't tested the XFCE fix (I don't have xfce set up) but the basic idea is that if the first `xfconf-query` command fails we try a second `xfconf-query` command. Can you test this out and let me know if it works?

**Comment by krook1024** [comment]
Sorry for the late response, I ran those commands you asked me for, here is the output.
`b1 ~/Pictures > ls
2Mzgepn.jpg       GoeuH3F.jpg  matterhorn_mountain_at_sunset-wallpaper-3840x2160.jpg  Screenshots
bbxvr1dnmg9y.jpg  HeMBCvx.jpg  oolHO8O.jpg

b1 ~/Pictures > xfconf-query --channel xfce4-desktop --property /backdrop/screen0/monitor0/image-path --set "/home/b1/Pictures/2Mzgepn.jpg" 
Property "/backdrop/screen0/monitor0/image-path" does not exist on channel "xfce4-desktop". If a new property should be created, use the --create option.

b1 ~/Pictures > echo "$?"
1`

Nothing happened to my wallpaper.

**Comment by dylanaraps** [comment]
Thanks for running those commands.

Try out the latest `wal` version and let me know if everything works, the output of `echo $?` tells me that the fix I implemented this morning should work. :)

**Comment by krook1024** [comment]
I'll gladly do it when I get back from school.

**Comment by krook1024** [comment]
Okay, now it works as a charm. Thank you for your work, this can be closed.

Have a nice day.
