### ISSUE TITLE
Add -R flag that reruns wal on last image

### ISSUE THREAD

**Issue by FlorianFranzen** [dylanaraps/wal#61]
I would like to suggest the addition of the ```-R``` flag that does the following:
```
wal -i "$(< "${HOME}/.cache/wal/wal")"
```

**Comment by dylanaraps** [comment]
Do we really need a new launch flag for this?

**Comment by FlorianFranzen** [comment]
I believe so. Running a bash-style command like this from i3 or polybar and getting the call to bash and all of the escaping right is cumbersome, not to mention that it breaks as soon as the location or name of the cache changes.

Having a simple flag that takes care of all of this will avoid all of these issues and should be straight forward to add.

**Comment by dylanaraps** [comment]
I've added `-R` to `pywal`. (*wal is no longer under active development.*)

If the Python `>3.6` requirement is an issue, `pywal` will soon support Python `3.5` (*and possibly `3.4` and below if there's a desire for it.*)
