### ISSUE TITLE
better integration with vim-airline

### ISSUE THREAD

**Issue by dagnachewa** [dylanaraps/wal#62]
Hello 
Is it possible to have a better integration with vim-airline ?
Thank you

**Comment by dylanaraps** [comment]
Please open an issue here: https://github.com/dylanaraps/wal.vim

Also, please elaborate on what you mean by "better integration".

**Comment by dagnachewa** [comment]
some of the colors generated by wal does not look good with vim-airline instead of colored arrows I see two white arrow

**Comment by dagnachewa** [comment]
Finally all is great now.
It was my mistake, dunno what I did, but now it works perfect
