### ISSUE TITLE
wal -ti fails with symlinks

### ISSUE THREAD

**Issue by wimstefan** [dylanaraps/wal#8]
I've created a symlink to my preferred wallpaper of the moment and try to call that with ```wal -ti```.
That works only if I change to the directory and call the symlink from there directly.
``` shell
11:04:16 [swimmer:~/system/wallpapers] % wal -ti default.jpg 
colors: Generated colorscheme
colors: Set terminal colors
wallpaper: Set new wallpaper
export: Exported escape sequences
export: Exported sh colors
export: Exported scss color variables
colors: Merged colors with X env
```

If I'm outside of that directory and try the same with a path I get the following:
```shell
11:04:20 [swimmer:~/system/wallpapers] % cd
11:04:27 [swimmer:~] % wal -ti ~/system/wallpapers/default.jpg 
/usr/local/bin/wal: line 260: cd: wal-rusty-winter-flower.jpg: Not a directory
Error: 'wal' must be run with '-i'
Try 'wal -h' for more information.
```

I'm using ```termite v12-13-g7738c76``` and ```zsh 5.3.1```

BTW ```"${HOME}/.cache/wal/wal"``` is missing on my system too ...

**Comment by dylanaraps** [comment]
I've figured out why this is happening. Thanks for finding this.

**Comment by dylanaraps** [comment]
I've fixed the issue, try out the latest master and let me know if the issue persists. :)

**Comment by wimstefan** [comment]
Thanks for you efforts but I'm afraid it still exists.

**Comment by dylanaraps** [comment]
Here's what I tested:

```sh
# Make a symlink called in my home directory
ln -s ~/Pictures/Wallpaper/10.jpg ~/wall.jpg

# All of these work *after* the fix.
wal -i wall.jpg
wal -i ~/wall.jpg
wal -i /home/dylan/wall.jpg
```

Are these the right reproduction steps or am I misunderstanding the issue here?

**Comment by wimstefan** [comment]
That's very interesting! I followed you example and created also a symlink in the home directory.

``` wal -ti ~/default.jpg ``` works and so does ``` wal -ti ~/system/wallpapers/default.jpg```. After removing ```~/default.jpg``` ``` wal -ti ~/system/wallpapers/default.jpg``` stops working ;-)

**Comment by dylanaraps** [comment]
Try out the latest master, I've simplified the function to **not** follow symlinks. `wal` instead uses the symlink itself as the argument. Hopefully this fixes the issue.

**Comment by wimstefan** [comment]
And we have a fix :smile:
Thank you very much for the swift reaction!

**Comment by dylanaraps** [comment]
Anytime :)
