### ISSUE TITLE
wal -i freeze on boot

### ISSUE THREAD

**Issue by jcmbass** [dylanaraps/wal#9]
each time I boot my computer the wal script does not work.
I have to write manually on terminal once then Ctrl-C then write it again in order for it to work.

can you please help with these. Thanks!

**Comment by dylanaraps** [comment]
Can you send me the exact commands you're using?

**Comment by jcmbass** [comment]
FIRST TIME I RUN IT:
jcmbass ~ >wal -i Pictures/wallpapers/ && wal-set
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/504.
convert: no images defined `txt:-' @ error/convert.c/ConvertImageCommand/3258.
Error: Imagemagick failed to generate a 16 color palette for 
Error: Imagemagick could only generate a 0 color palette.
Error: wal won't do guesswork to fill in the blanks.
Error: Please try a different image.

THEN SECOND TIME:
jcmbass ~ >wal -i Pictures/wallpapers/ && wal-set
colors: Generated colorscheme
colors: Set terminal colors
wallpaper: Set new wallpaper
export: Exported escape sequences
export: Exported sh colors
export: Exported scss color variables
colors: Merged colors with X env

**Comment by dylanaraps** [comment]
It looks like the image shuffle is failing to return a valid image. I'll look into this. Thanks

**Comment by dylanaraps** [comment]
Try out the latest master and let me know if it still occurs. The issue *should* be fixes but there's still a chance that it'll occur.

**Comment by jcmbass** [comment]
that fix it. Thanks for taking the time and fix it.

**Comment by dylanaraps** [comment]
Awesome. :)
